### ISSUE TITLE
Support aggregation arguments being objects

### ISSUE THREAD

**Issue by mindrones** [nestauk/dapsboard#59]
For aggregations like `histogram`, where some arguments are objects [1] the form needs to show a label corrrespondent to the argument (e.g. `extended_bounds`) and then indented inputs corresponding to that argument fields (e.g. `min` and `max`).

[1] pseudo-code
```
histogram (
    field: string,
    interval: number
    [, min_doc_count: integer]
    [, extended_bounds: {
      min: number,
      max: number
    }]
    [, keyed: boolean]
    [, missing: number]
    [, order: {
      [_count: string = 'asc'|'desc'],
      [_key: string = 'asc'|'desc'],
      [<subaggr_key>: string = 'asc'|'desc'],
      [<subaggr_key>.<key>: string = 'asc'|'desc'],
    }]
)
```

**Comment by saabi** [comment]
There're are some regularities in the formats suggesting that a common editor could be implented for them. For example ranges have a `from` and `to` field, but they might accept different formats and semantics in their values dependeng on the aggregation (range, date_range, ip_range)

Besides ranges, some aggrregations also support filtering, which are specified using most of the ES querying DSL besides aggregations, so supporting that in Dapsboard might be quite a bit of work.

Other object formats that are used in some aggregation parameters are subsets of the aggregation DSL itself (`sources` parameter in `composite`) and sorting parameters.

In conclusion, it might be convenient to provide specialized components for at least a few of these parameters (sorting, ranges and perhaps also filtering and parameters that accept aggregation queries) instead of a more generic recursive property editor.

### Bucket Aggregations

* filter and filters: Seems to require understanding of most ES querying capabilities such as `match` and `term`
* adjacency_matrix
  * filters: Seems to use the same querying capabilities used in the above aggreation type
* composite
  * sources: List of objects that are themselves a limited form of aggregation queries
* date_range
  * ranges: multi prop object `{to:'...', from: '...'}` specifying ranges
* geo_distance
  * ranges: list of range objects specifying distances  `{to: number, from: number}`
* ip_ranges: list of range objects specifying distances  `{to:'0.0.0.0', from: '0.0.0.0'}`
* range: list of range objects specifying distances  `{to: number, from: number}`
* significant_terms:
  * background_filter: object with single property `term` (type ???)
  * jlh: An empty object `{}` (presumably reserved for future parameters?)
  * chi_square: An empty object `{}` (presumably reserved for future parameters?)
  * gnd: An empty object `{}` (presumably reserved for future parameters?)
  * percentage: An empty object `{}` (presumably reserved for future parameters?)
  * mutual_information: object with single boolean property `include_negatives`
  * background_filter: Custom background context. Filter object format (as in non aggregation queries)

* significant_text:
  * background_filter: object with single property `term` (type ???)
  * source_fields: array of field names

Type unions of explicit strings not included above.

**Comment by saabi** [comment]
Waiting for #103 before proceeding
